---
title: "`cape` Simulation Study"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  \VignetteIndexEntry{Simulation study}
  \VignetteEngine{knitr::rmarkdown}
  \VignetteEncoding{UTF-8}
---

```{r}
library(cape)
```

# 2. Simulation Study

# 2.1. Settings

```{r setting, fig.align='center'}
# Number of Monte-Carlo simulations 
B = 10^4

# Initial simulation seed
seed = 1832  

# Simulation settings
simu = data.frame(Simulation = 1:270,
                  p0 = 100*rep(c(rep(5/100, 30), rep(20/100, 30), rep(75/100, 30)), 3),
                  pi0 = 100*c(rep(c(seq(from = 1/1000, to = 5/100 - 1/1000, length.out = 30),
                                seq(from = 1/1000, to = 20/100 - 2.5/1000, length.out = 30),
                                seq(from = 1/1000, to = 75/100 - 5/1000, length.out = 30)), 2),
                              rep(c(seq(from = 1/100 + 1/1000, to = 5/100 - 1/1000, length.out = 30),
                                seq(from = 1/100 + 1/1000, to = 20/100 - 2.5/1000, length.out = 30),
                                seq(from = 1/100 + 1/1000, to = 75/100 - 5/1000, length.out = 30)), 1)),
                  n = rep(2000, 30*9),
                  alpha = 100*c(rep(0, 90), rep(0, 90), rep(0.01,90)),
                  beta = 100*c(rep(0, 90), rep(0.02,90), rep(0.02,90)))
```

## 2.2. Simulation Code

```{r simu, cache = TRUE}
# Initialisation       
m = tail(simu$Simulation, n=1)
error_survey = error_moment = error_mle = error_mmle = matrix(NA, B, m)
length_survey_cp = length_moment_cp = matrix(NA, B, m)  
length_survey_asy = length_moment_asy = length_mle_asy = length_mmle_asy = matrix(NA, B, m) 
coverage_survey_cp = coverage_moment_cp = matrix(NA, B, m)  
coverage_survey_asy = coverage_moment_asy = coverage_mle_asy = coverage_mmle_asy = matrix(NA, B, m)  

# Start Monte-Carlo   
for (j in 1:m){
  for (i in 1:B){ 
    set.seed(i)
    # Simulate data 
    X = sim_Rs(n = simu$n[j], 
               theta = simu$p0[j]/100, 
               pi0 = simu$pi0[j]/100, 
               alpha = simu$alpha[j]/100, 
               beta = simu$beta[j]/100, 
               alpha0 = simu$alpha[j]/100, 
               beta0 = simu$beta[j]/100)
    
    # ----------------------------------------------------
    # Fit survey sample estimator
    # ----------------------------------------------------
    survey = survey_sample(R = X$R1 + X$R3, n = X$n, 
                           alpha = X$alpha, beta = X$beta, 
                           pi0 = X$pi0, simulation = TRUE) 
    
    # Estimation error
    error_survey[i,j] = survey$estimate - simu$p0[j]/100
    
    # Coverage - CP
    coverage_survey_cp[i,j] = survey$ci_cp[1] < simu$p0[j]/100 && survey$ci_cp[2] > simu$p0[j]/100
    length_survey_cp[i,j] = diff(survey$ci_cp)
    
    # Coverage - Asym
    coverage_survey_asy[i,j] = survey$ci_asym[1] < simu$p0[j]/100 && survey$ci_asym[2] > simu$p0[j]/100
    if (is.na(sum(survey$ci_asym))){
      length_survey_asy[i,j] = NA
    }else{
      length_survey_asy[i,j] = diff(survey$ci_asym)
    }
    
    # ----------------------------------------------------
    # Fit moment estimator
    # ----------------------------------------------------
    moment_estim = moment_estimator(R3 = X$R3, n = X$n, pi0 = X$pi0,
                           alpha0 = X$alpha0, alpha = X$alpha,
                           beta0 = X$beta0, beta = X$beta) 
    
    # Estimation error
    error_moment[i,j] = moment_estim$estimate - simu$p0[j]/100
    
    # Coverage - CP
    coverage_moment_cp[i,j] = moment_estim$ci_cp[1] < simu$p0[j]/100 && moment_estim$ci_cp[2] > simu$p0[j]/100
    length_moment_cp[i,j] = diff(moment_estim$ci_cp)
    
    # Coverage - Asym
    coverage_moment_asy[i,j] = moment_estim$ci_asym[1] < simu$p0[j]/100 && moment_estim$ci_asym[2] > simu$p0[j]/100
    length_moment_asy[i,j] = diff(moment_estim$ci_asym)
    
    
    # ----------------------------------------------------
    # Fit MLE
    # ----------------------------------------------------
    mle_estim = mle(R1 = X$R1, R2 = X$R2, R3 = X$R3, R4 = X$R4, 
                    n = X$n, pi0 = X$pi0, alpha = X$alpha, 
                    beta = X$beta, alpha0 = X$alpha0, beta0 = X$beta0)
    
    # Estimation error
    error_mle[i,j] = mle_estim$estimate - simu$p0[j]/100
    
    # Coverage - Asym
    coverage_mle_asy[i,j] = mle_estim$ci_asym[1] < simu$p0[j]/100 && mle_estim$ci_asym[2] > simu$p0[j]/100
    length_mle_asy[i,j] = diff(mle_estim$ci_asym)
    
    # ----------------------------------------------------
    # Fit Marginal MLE
    # ----------------------------------------------------
    marginal_mle_estim = marginal_mle(R1 = X$R1, R3 = X$R3, n = X$n, pi0 = X$pi0, 
                  alpha = X$alpha, beta = X$beta, alpha0 = X$alpha0, 
                  beta0 = X$beta0) 
    
    # Estimation error
    error_mmle[i,j] = marginal_mle_estim$estimate - simu$p0[j]/100
    
    # Coverage - Asym
    coverage_mmle_asy[i,j] = marginal_mle_estim$ci_asym[1] < simu$p0[j]/100 && marginal_mle_estim$ci_asym[2] > simu$p0[j]/100
    length_mmle_asy[i,j] = diff(marginal_mle_estim$ci_asym)

  } 
}
```

## 2.3 Figure: Point Estimation Ratio of RMSE

```{r, fig.align='center', fig.width=10, fig.height=9, echo = FALSE}
RMSE = function(x)
  sqrt(mean(x)^2 + var(x))

cols = hcl(h = seq(15, 375, length = 4), l = 65, c = 100)[1:3]

rmse_survey = apply(error_survey, 2, RMSE)
rmse_mle = apply(error_mle, 2, RMSE)
rmse_mmle = apply(error_mmle, 2, RMSE)
rmse_mom = apply(error_moment, 2, RMSE)

par(mfrow = c(3,3), mar = c(0.5,0.5,0.5,0.5), oma = c(5,5,3,0))
plot(NA, xlim = c(0,5/100), ylim = c(0, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
axis(2)
grid()
box()
abline(h = 1, lwd = 2)
lines(simu$pi0[1:30]/100, rmse_mle[1:30]/rmse_survey[1:30], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[1:30]/100, rmse_mle[1:30]/  rmse_mmle[1:30], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[1:30]/100, rmse_mle[1:30]/   rmse_mom[1:30], col = cols[2], pch = 17, type = "l", lwd = 2)
mtext("No measurement error", side = 2, line = 3)
mtext(expression(paste(p[0],"= 5%")), side = 3, line = 1)

plot(NA, xlim = c(0,20/100), ylim = c(0, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 1, lwd = 2)
lines(simu$pi0[31:60]/100, rmse_mle[31:60]/rmse_survey[31:60], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[31:60]/100, rmse_mle[31:60]/  rmse_mmle[31:60], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[31:60]/100, rmse_mle[31:60]/   rmse_mom[31:60], col = cols[2], pch = 17, type = "l", lwd = 2)
mtext(expression(paste(p[0],"= 20%")), side = 3, line = 1)

plot(NA, xlim = c(0,75/100), ylim = c(0, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 1, lwd = 2)
lines(simu$pi0[61:90]/100, rmse_mle[61:90]/rmse_survey[61:90], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[61:90]/100, rmse_mle[61:90]/  rmse_mmle[61:90], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[61:90]/100, rmse_mle[61:90]/   rmse_mom[61:90], col = cols[2], pch = 17, type = "l", lwd = 2)
mtext(expression(paste(p[0],"= 75%")), side = 3, line = 1)

plot(NA, xlim = c(0,5/100), ylim = c(0, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
axis(2)
grid()
box()
abline(h = 1, lwd = 2)
lines(simu$pi0[91:120]/100, rmse_mle[91:120]/rmse_survey[91:120], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[91:120]/100, rmse_mle[91:120]/  rmse_mmle[91:120], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[91:120]/100, rmse_mle[91:120]/   rmse_mom[91:120], col = cols[2], pch = 17, type = "l", lwd = 2)
mtext("with false positive", side = 2, line = 3)

plot(NA, xlim = c(0,20/100), ylim = c(0, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 1, lwd = 2)
lines(simu$pi0[121:150]/100, rmse_mle[121:150]/rmse_survey[121:150], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[121:150]/100, rmse_mle[121:150]/  rmse_mmle[121:150], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[121:150]/100, rmse_mle[121:150]/   rmse_mom[121:150], col = cols[2], pch = 17, type = "l", lwd = 2)

plot(NA, xlim = c(0,75/100), ylim = c(0, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 1, lwd = 2)
lines(simu$pi0[151:180]/100, rmse_mle[151:180]/rmse_survey[151:180], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[151:180]/100, rmse_mle[151:180]/  rmse_mmle[151:180], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[151:180]/100, rmse_mle[151:180]/   rmse_mom[151:180], col = cols[2], pch = 17, type = "l", lwd = 2)


plot(NA, xlim = c(0,5/100), ylim = c(0, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
axis(2)
grid()
box()
axis(1)
abline(h = 1, lwd = 2)
lines(simu$pi0[181:210]/100, rmse_mle[181:210]/rmse_survey[181:210], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[181:210]/100, rmse_mle[181:210]/  rmse_mmle[181:210], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[181:210]/100, rmse_mle[181:210]/   rmse_mom[181:210], col = cols[2], pch = 17, type = "l", lwd = 2)
mtext("with false positive and negative", side = 2, line = 3)
mtext(expression(paste(pi[0])), side = 1, line = 3)

legend(0, 0.4, c("Survey Sample", "Marginal MLE", "Moment Estimator"), col = cols[c(1,3,2)],
       lwd = 2, bty = "n")

plot(NA, xlim = c(0,20/100), ylim = c(0, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
axis(1)
abline(h = 1, lwd = 2)
lines(simu$pi0[211:240]/100, rmse_mle[211:240]/rmse_survey[211:240], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[211:240]/100, rmse_mle[211:240]/  rmse_mmle[211:240], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[211:240]/100, rmse_mle[211:240]/   rmse_mom[211:240], col = cols[2], pch = 17, type = "l", lwd = 2)
mtext(expression(paste(pi[0])), side = 1, line = 3)

plot(NA, xlim = c(0,75/100), ylim = c(0, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
axis(1)
abline(h = 1, lwd = 2)
lines(simu$pi0[241:270]/100, rmse_mle[241:270]/rmse_survey[241:270], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[241:270]/100, rmse_mle[241:270]/  rmse_mmle[241:270], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[241:270]/100, rmse_mle[241:270]/   rmse_mom[241:270], col = cols[2], pch = 17, type = "l", lwd = 2)
mtext(expression(paste(pi[0])), side = 1, line = 3)
```

## 2.4 Figure: 95% Coverage

```{r, fig.align='center', fig.width=10, fig.height=9, echo=FALSE}
cov_survey = 100*apply(coverage_survey_cp, 2, mean)
cov_mle = 100*apply(coverage_mle_asy, 2, mean)
cov_mom_cp = 100*apply(coverage_moment_cp, 2, mean)
cov_mom_asym = 100*apply(coverage_moment_asy, 2, mean)
cols = hcl(h = seq(15, 375, length = 4), l = 65, c = 100)[1:3]

par(mfrow = c(3,3), mar = c(0.5,0.5,0.5,0.5), oma = c(5,5,3,0))
plot(NA, xlim = c(0,5/100), ylim = c(86, 99), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
axis(2)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[1:30]/100, cov_survey[1:30], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[1:30]/100, cov_mle[1:30], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[1:30]/100, cov_mom_cp[1:30], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[1:30]/100, cov_mom_asym[1:30], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)

mtext("No measurement error", side = 2, line = 3)
mtext(expression(paste(p[0],"= 5%")), side = 3, line = 1)


plot(NA, xlim = c(0,20/100), ylim = c(86, 99), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[31:60]/100,   cov_survey[31:60], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[31:60]/100,      cov_mle[31:60], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[31:60]/100,   cov_mom_cp[31:60], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[31:60]/100, cov_mom_asym[31:60], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)

mtext(expression(paste(p[0],"= 20%")), side = 3, line = 1)


plot(NA, xlim = c(0,75/100), ylim = c(86, 99), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[61:90]/100,   cov_survey[61:90], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[61:90]/100,      cov_mle[61:90], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[61:90]/100,   cov_mom_cp[61:90], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[61:90]/100, cov_mom_asym[61:90], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)

mtext(expression(paste(p[0],"= 75%")), side = 3, line = 1)



plot(NA, xlim = c(0,5/100), ylim = c(86, 99), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
axis(2)
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[91:120]/100,   cov_survey[91:120], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[91:120]/100,      cov_mle[91:120], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[91:120]/100,   cov_mom_cp[91:120], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[91:120]/100, cov_mom_asym[91:120], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)

mtext("With false positive", side = 2, line = 3)


plot(NA, xlim = c(0,20/100), ylim = c(86, 99), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[121:150]/100,   cov_survey[121:150], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[121:150]/100,      cov_mle[121:150], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[121:150]/100,   cov_mom_cp[121:150], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[121:150]/100, cov_mom_asym[121:150], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)


plot(NA, xlim = c(0,75/100), ylim = c(86, 99), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[151:180]/100,   cov_survey[151:180], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[151:180]/100,      cov_mle[151:180], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[151:180]/100,   cov_mom_cp[151:180], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[151:180]/100, cov_mom_asym[151:180], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)


plot(NA, xlim = c(0,5/100), ylim = c(86, 99), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
axis(2)
axis(1)
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[181:210]/100,   cov_survey[181:210], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[181:210]/100,      cov_mle[181:210], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[181:210]/100,   cov_mom_cp[181:210], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[181:210]/100, cov_mom_asym[181:210], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)

mtext("With false positive and negative", side = 2, line = 3)
mtext(expression(paste(pi[0])), side = 1, line = 3)

legend(0, 90, c("Survey Sample - CP.", "MLE - Asym.", "Moment - CP."), col = cols[c(1,3,2)],
       lwd = 2, bty = "n")

plot(NA, xlim = c(0,20/100), ylim = c(86, 99), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
axis(1)
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[211:240]/100,   cov_survey[211:240], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[211:240]/100,      cov_mle[211:240], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[211:240]/100,   cov_mom_cp[211:240], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[211:240]/100, cov_mom_asym[211:240], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)
mtext(expression(paste(pi[0])), side = 1, line = 3)

plot(NA, xlim = c(0,75/100), ylim = c(86, 99), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
axis(1)
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[241:270]/100,   cov_survey[241:270], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[241:270]/100,      cov_mle[241:270], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[241:270]/100,   cov_mom_cp[241:270], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[241:270]/100, cov_mom_asym[241:270], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)
mtext(expression(paste(pi[0])), side = 1, line = 3)



```

## 2.5 Figure: Ratio of mean length of 95% CI

```{r, fig.align='center', fig.width=10, fig.height=9, echo = FALSE}
len_survey = 100*apply(length_survey_cp, 2, mean)
len_mle = 100*apply(length_mle_asy, 2, mean)
len_mmle = 100*apply(length_mmle_asy, 2, mean)
len_mom_cp = 100*apply(length_moment_cp, 2, mean)
#cov_mom_asym = 100*apply(length_moment_asy, 2, mean)
cols = hcl(h = seq(15, 375, length = 4), l = 65, c = 100)[1:3]

par(mfrow = c(3,3), mar = c(0.5,0.5,0.5,0.5), oma = c(5,5,3,0))
plot(NA, xlim = c(0,5/100), ylim = c(0.25, 1.55), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
axis(2)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[1:30]/100, len_mle[1:30]/len_survey[1:30], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[1:30]/100, len_mle[1:30]/len_mmle[1:30], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[1:30]/100, len_mle[1:30]/len_mom_cp[1:30], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[1:30]/100, cov_mom_asym[1:30], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)

mtext("No measurement error", side = 2, line = 3)
mtext(expression(paste(p[0],"= 5%")), side = 3, line = 1)

plot(NA, xlim = c(0,20/100), ylim = c(0.25, 1.55), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[31:60]/100, len_mle[31:60]/len_survey[31:60], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[31:60]/100, len_mle[31:60]/  len_mmle[31:60], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[31:60]/100, len_mle[31:60]/len_mom_cp[31:60], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[1:30]/100, cov_mom_asym[1:30], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)

mtext(expression(paste(p[0],"= 20%")), side = 3, line = 1)


plot(NA, xlim = c(0,75/100), ylim = c(0.25, 1.55), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[61:90]/100, len_mle[61:90]/len_survey[61:90], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[61:90]/100, len_mle[61:90]/  len_mmle[61:90], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[61:90]/100, len_mle[61:90]/len_mom_cp[61:90], col = cols[2], pch = 17, type = "l", lwd = 2)
#lines(simu$pi0[1:30]/100, cov_mom_asym[1:30], col = cols[2], pch = 17, type = "l", lwd = 2, lty = 2)

mtext(expression(paste(p[0],"= 75%")), side = 3, line = 1)


plot(NA, xlim = c(0,5/100), ylim = c(0.25, 1.55), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
axis(2)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[91:120]/100, len_mle[91:120]/ len_survey[91:120], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[91:120]/100, len_mle[91:120]/   len_mmle[91:120], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[91:120]/100, len_mle[91:120]/ len_mom_cp[91:120], col = cols[2], pch = 17, type = "l", lwd = 2)

mtext("With false positive", side = 2, line = 3)

plot(NA, xlim = c(0,20/100), ylim = c(0.25, 1.55), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[121:150]/100, len_mle[121:150]/len_survey[121:150], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[121:150]/100, len_mle[121:150]/  len_mmle[121:150], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[121:150]/100, len_mle[121:150]/len_mom_cp[121:150], col = cols[2], pch = 17, type = "l", lwd = 2)

plot(NA, xlim = c(0,75/100), ylim = c(0.25, 1.55), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[151:180]/100, len_mle[151:180]/len_survey[151:180], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[151:180]/100, len_mle[151:180]/  len_mmle[151:180], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[151:180]/100, len_mle[151:180]/len_mom_cp[151:180], col = cols[2], pch = 17, type = "l", lwd = 2)


plot(NA, xlim = c(0,5/100), ylim = c(0.25, 1.55), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
axis(2)
grid()
axis(1)
box()
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[181:210]/100, len_mle[181:210]/ len_survey[181:210], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[181:210]/100, len_mle[181:210]/   len_mmle[181:210], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[181:210]/100, len_mle[181:210]/ len_mom_cp[181:210], col = cols[2], pch = 17, type = "l", lwd = 2)

mtext("With false positive and negative", side = 2, line = 3)
mtext(expression(paste(pi[0])), side = 1, line = 3)

legend(0, 90, c("Survey Sample - CP.", "Marginal MLE - Asym.", "Moment - CP."), col = cols[c(1,3,2)],
       lwd = 2, bty = "n")

plot(NA, xlim = c(0,20/100), ylim = c(0.25, 1.55), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
axis(1)
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[211:240]/100, len_mle[211:240]/len_survey[211:240], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[211:240]/100, len_mle[211:240]/  len_mmle[211:240], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[211:240]/100, len_mle[211:240]/len_mom_cp[211:240], col = cols[2], pch = 17, type = "l", lwd = 2)
mtext(expression(paste(pi[0])), side = 1, line = 3)


plot(NA, xlim = c(0,75/100), ylim = c(0.25, 1.55), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
grid()
box()
axis(1)
abline(h = 95, lwd = 2, lty = 2)
lines(simu$pi0[241:270]/100, len_mle[241:270]/len_survey[241:270], col = cols[1], pch = 15, type = "l", lwd = 2)
lines(simu$pi0[241:270]/100, len_mle[241:270]/  len_mmle[241:270], col = cols[3], pch = 16, type = "l", lwd = 2)
lines(simu$pi0[241:270]/100, len_mle[241:270]/len_mom_cp[241:270], col = cols[2], pch = 17, type = "l", lwd = 2)
mtext(expression(paste(pi[0])), side = 1, line = 3)
```



```{r, fig.align='center', fig.width=10, fig.height=6, eval=FALSE, echo = FALSE}
RMSE = function(x)
  sqrt(mean(x)^2 + var(x))

nb_settings = tail(simu$Simulation, n=1)
cols = hcl(h = seq(15, 375, length = 4), l = 65, c = 100)[1:3]

rmse_survey = apply(error_survey, 2, RMSE)
rmse_mle = apply(error_mle, 2, RMSE)
rmse_mmle = apply(error_mmle, 2, RMSE)
rmse_mom = apply(error_moment, 2, RMSE)
 
par(mfrow = c(3,3), mar = c(0.5,0.5,0.5,0.5), oma = c(5,5,3,0))

plot(NA, xlim = c(1,nb_settings), ylim = c(0.2, 1.05), xlab = "Simulation ID", ylab = "Ratio of RMSE", axes = FALSE)
rect(0.5, -0.01, 5.5, 1.1, col = "grey95", border = "grey95")
rect(10.5, -0.01, 15.5, 1.1, col = "grey95", border = "grey95")
rect(20.5, -0.01, 25.5, 1.1, col = "grey95", border = "grey95")
text(3.5, 0.25, "n = 1,500")
text(8.5, 0.25, "n = 15,000")
text(13.5, 0.25, "n = 1,500")
text(18.5, 0.25, "n = 15,000")
text(23.5, 0.25, "n = 1,500")
text(28.5, 0.25, "n = 15,000")
text(5.5, 1.04, "without measurement error")
text(15.5, 1.04, "with false positive")
text(25.5, 1.04, "with false positive and negative")
abline(v = 10.5, lwd = 2, lty = 2)
abline(v = 20.5, lwd = 2, lty = 2)
axis(1, 1:nb_settings, cex.axis = 0.9)
axis(2)
grid()
abline(v = 1:nb_settings, col = "grey80", lty = 3)
abline(h = (0:20)/10, col = "grey80", lty = 3)
box()
abline(h = 1, lwd = 2)
lines(1:nb_settings, rmse_mle/rmse_survey, col = cols[1], pch = 15, type = "b")
lines(1:nb_settings, rmse_mle/rmse_mmle, col = cols[3], pch = 16, type = "b")
lines(1:nb_settings, rmse_mle/rmse_mom, col = cols[2], pch = 17, type = "b")

abline(h = 1, lwd = 2)
legend(24, 0.55, c("Survey Sample", "Marginal MLE", "Moment Estimator"), col = cols[c(1,3,2)],
       pch = c(15, 16, 17), lwd = 1, bty = "n")
```



```{r, fig.width=10, fig.height=10, eval = FALSE, echo = FALSE}
par(mfrow = c(2,1), mar = c(0.5,0.5,0.5,0.5), oma = c(5,5,3,0))

# Compute empirical coverage
cov_survey_cp = 100*apply(coverage_survey_cp, 2, mean)
cov_survey_asy = 100*apply(coverage_survey_asy, 2, mean, na.rm = TRUE)
cov_moment_cp = 100*apply(coverage_moment_cp, 2, mean)
cov_moment_asy = 100*apply(coverage_moment_asy, 2, mean)
cov_mle = 100*apply(coverage_mle_asy, 2, mean)
cov_mmle = 100*apply(coverage_mmle_asy, 2, mean)

# Compute average length of CI
len_survey_cp = apply(length_survey_cp, 2, mean)
len_moment_cp = apply(length_moment_cp, 2, mean)
len_mle_asy = apply(length_mle_asy, 2, mean)
len_moment_asy = apply(length_moment_asy, 2, mean)

# Plot coverage
plot(NA, xlim = c(1,nb_settings), ylim = c(78.5, 100.8), xlab = " ", ylab = " ", axes = FALSE)
rect(0.5, 0, 5.5, 150, col = "grey95", border = "grey95")
rect(10.5, 0, 15.5, 150, col = "grey95", border = "grey95")
rect(20.5, 0, 25.5, 150, col = "grey95", border = "grey95")
text(3.5, 94, "n = 1,500")
text(8.5, 94, "n = 15,000")
text(13.5, 94, "n = 1,500")
text(18.5, 94, "n = 15,000")
text(23.5, 94, "n = 1,500")
text(28.5, 94, "n = 15,000")
text(5.5, 100.5, "without measurement error")
text(15.5, 100.5, "with false positive")
text(25.5, 100.5, "with false positive and negative")
abline(v = 10.5, lwd = 2, lty = 2)
abline(v = 20.5, lwd = 2, lty = 2)
axis(2)
grid()
abline(v = 1:nb_settings, col = "grey80", lty = 3)
abline(h = 90 + (0:10), col = "grey80", lty = 3)
box()
abline(h = 95, lwd = 2)
mtext("Empirical coverage (95% conf. level)", side = 2, line = 3)
#lines(cov_survey, col = cols[1], pch = 16, type = "b")
#lines(cov_mle, col = cols[2], pch = 17, type = "b")
#lines(cov_int_mle, col = cols[3], pch = 15, type = "b")
#lines(cov_survey_asy, col = cols[4], pch = 18, type = "b")


#lines(1:nb_settings, cov_survey_asy, col = cols[1], pch = 15, type = "l", lty = 1)
lines(1:nb_settings, cov_survey_cp, col = cols[1], pch = 15, type = "l", lty = 2)
#lines(1:nb_settings, cov_mmle, col = cols[3], pch = 16, type = "b", lty = 1)
lines(1:nb_settings, cov_moment_asy, col = cols[2], pch = 17, type = "b", lty = 1)
lines(1:nb_settings, cov_moment_cp, col = cols[2], pch = 17, type = "b", lty = 2)
lines(1:nb_settings, cov_mle, col = cols[3], pch = 18, type = "b", lty = 1)



#legend(2.5, 99.5, c("Survey Sample (CP)", "MLE", "M-MLE"), col = cols[c(1,2, 3)],
#       pch = c(16, 17, 15), lwd = 1, bty = "n")


plot(NA, xlim = c(1,nb_settings), ylim = c(0.25, 1.55), xlab = " ", ylab = " ", axes = FALSE)
rect(0.5, 0, 5.5, 1.50, col = "grey95", border = "grey95")
rect(10.5, 0, 15.5, 1.50, col = "grey95", border = "grey95")
rect(20.5, 0, 25.5, 1.50, col = "grey95", border = "grey95")
text(3.5, 0.59, "n = 1,500")
text(8.5, 0.59, "n = 15,000")
text(13.5, 0.59, "n = 1,500")
text(18.5, 0.59, "n = 15,000")
text(23.5, 0.59, "n = 1,500")
text(28.5, 0.59, "n = 15,000")
text(5.5, 1.01, "without measurement error")
text(15.5, 1.01, "with false positive")
text(25.5, 1.01, "with false positive and negative")
abline(v = 8.5, lwd = 2, lty = 2)
abline(v = 16.5, lwd = 2, lty = 2)
axis(2)
axis(1, at = 1:24)
grid()
abline(v = 1:nb_settings, col = "grey80", lty = 3)
abline(h = (0:10)/10, col = "grey80", lty = 3)
box()
mtext("Ratio of average length of 95% CI", side = 2, line = 3)
mtext("Simulation ID", side = 1, line = 2)
abline(h = 1, lwd = 2)
cols2 = hcl(h = seq(15, 375, length = 5), l = 65, c = 100)[1:4]
lines(len_mle_asy/len_moment_cp, type = "b", ylim = c(0.6, 1.01),
      col = cols2[4], pch = 18, cex = 1.4)
lines(len_mle_asy/len_survey_cp, type = "b", ylim = c(0.6, 1.01),
      col = cols2[3], pch = 17, cex = 1.4)
#lines(len_mle_asy/len_moment_asy, type = "b", ylim = c(0.6, 1.01),
#      col = cols2[1], pch = 17, cex = 1.4)
```
